sonar.projectKey=YOUR_GITHUB_USERNAME_ticket-booking-service
sonar.organization=YOUR_SONAR_ORG
sonar.sources=app
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.exclusions=**/__pycache__/**,**/*.pyc,frontend/**
