sonar.projectKey=ridmikaw_ticket-booking-service
sonar.organization=ridmikaw
sonar.sources=app
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.exclusions=**/__pycache__/**,**/*.pyc
